# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SIMPLUS.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1146, 635)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget_Main = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget_Main.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget_Main.sizePolicy().hasHeightForWidth())
        self.tabWidget_Main.setSizePolicy(sizePolicy)
        self.tabWidget_Main.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget_Main.setObjectName("tabWidget_Main")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget_Analytical = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_Analytical.setMovable(True)
        self.tabWidget_Analytical.setObjectName("tabWidget_Analytical")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.AnalyticalModelPlotLayout = QtWidgets.QVBoxLayout()
        self.AnalyticalModelPlotLayout.setObjectName("AnalyticalModelPlotLayout")
        self.AnalyticalModelgraphicsView = MplWidgetAnalytic(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AnalyticalModelgraphicsView.sizePolicy().hasHeightForWidth())
        self.AnalyticalModelgraphicsView.setSizePolicy(sizePolicy)
        self.AnalyticalModelgraphicsView.setObjectName("AnalyticalModelgraphicsView")
        self.AnalyticalModelPlotLayout.addWidget(self.AnalyticalModelgraphicsView)
        self.gridLayout.addLayout(self.AnalyticalModelPlotLayout, 0, 0, 1, 1)
        self.tabWidget_Analytical.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_Analytical.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.AnalyticalModelInfoLayout = QtWidgets.QVBoxLayout()
        self.AnalyticalModelInfoLayout.setObjectName("AnalyticalModelInfoLayout")
        self.graphicsViewInfoAnalytical = MplWidgetInfo(self.tab_5)
        self.graphicsViewInfoAnalytical.setObjectName("graphicsViewInfoAnalytical")
        self.AnalyticalModelInfoLayout.addWidget(self.graphicsViewInfoAnalytical)
        self.gridLayout_3.addLayout(self.AnalyticalModelInfoLayout, 0, 0, 1, 1)
        self.tabWidget_Analytical.addTab(self.tab_5, "")
        self.horizontalLayout_2.addWidget(self.tabWidget_Analytical)
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 280, 520))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_ModelAnalytical = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBox_ModelAnalytical.setObjectName("comboBox_ModelAnalytical")
        self.verticalLayout_2.addWidget(self.comboBox_ModelAnalytical)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.treeWidget_Analytical = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_Analytical.sizePolicy().hasHeightForWidth())
        self.treeWidget_Analytical.setSizePolicy(sizePolicy)
        self.treeWidget_Analytical.setIndentation(10)
        self.treeWidget_Analytical.setObjectName("treeWidget_Analytical")
        self.treeWidget_Analytical.headerItem().setTextAlignment(0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_Analytical)
        self.verticalLayout_2.addWidget(self.treeWidget_Analytical)
        self.pushButtonEmail1 = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButtonEmail1.setObjectName("pushButtonEmail1")
        self.verticalLayout_2.addWidget(self.pushButtonEmail1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pushButton_RunAnalytical = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_RunAnalytical.setObjectName("pushButton_RunAnalytical")
        self.horizontalLayout_11.addWidget(self.pushButton_RunAnalytical)
        self.showLegendAnalytical = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.showLegendAnalytical.setObjectName("showLegendAnalytical")
        self.horizontalLayout_11.addWidget(self.showLegendAnalytical)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addLayout(self.verticalLayout_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.tabWidget_Main.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tabWidget_Numerical = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_Numerical.setObjectName("tabWidget_Numerical")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_7)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.NumericalModelPlotLayout = QtWidgets.QVBoxLayout()
        self.NumericalModelPlotLayout.setObjectName("NumericalModelPlotLayout")
        self.NumericalModelgraphicsView = MplWidgetNumerical(self.tab_7)
        self.NumericalModelgraphicsView.setObjectName("NumericalModelgraphicsView")
        self.NumericalModelPlotLayout.addWidget(self.NumericalModelgraphicsView)
        self.gridLayout_4.addLayout(self.NumericalModelPlotLayout, 0, 0, 1, 1)
        self.tabWidget_Numerical.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.tabWidget_Numerical.addTab(self.tab_8, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_6)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.NumericalModelInfoLayout = QtWidgets.QVBoxLayout()
        self.NumericalModelInfoLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.NumericalModelInfoLayout.setObjectName("NumericalModelInfoLayout")
        self.graphicsViewInfoNumerical = MplWidgetInfo(self.tab_6)
        self.graphicsViewInfoNumerical.setObjectName("graphicsViewInfoNumerical")
        self.NumericalModelInfoLayout.addWidget(self.graphicsViewInfoNumerical)
        self.gridLayout_2.addLayout(self.NumericalModelInfoLayout, 0, 0, 1, 1)
        self.tabWidget_Numerical.addTab(self.tab_6, "")
        self.horizontalLayout_12.addWidget(self.tabWidget_Numerical)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 280, 520))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox_ModelNumerical = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_ModelNumerical.setEnabled(True)
        self.comboBox_ModelNumerical.setObjectName("comboBox_ModelNumerical")
        self.verticalLayout.addWidget(self.comboBox_ModelNumerical)
        self.comboBox_EquationSolverType = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_EquationSolverType.setObjectName("comboBox_EquationSolverType")
        self.comboBox_EquationSolverType.addItem("")
        self.comboBox_EquationSolverType.addItem("")
        self.verticalLayout.addWidget(self.comboBox_EquationSolverType)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777214, 25))
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.treeWidget_Numerical = QtWidgets.QTreeWidget(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeWidget_Numerical.sizePolicy().hasHeightForWidth())
        self.treeWidget_Numerical.setSizePolicy(sizePolicy)
        self.treeWidget_Numerical.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeWidget_Numerical.setIndentation(10)
        self.treeWidget_Numerical.setObjectName("treeWidget_Numerical")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget_Numerical)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.verticalLayout.addWidget(self.treeWidget_Numerical)
        self.pushButtonEmail2 = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButtonEmail2.setObjectName("pushButtonEmail2")
        self.verticalLayout.addWidget(self.pushButtonEmail2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.pushButton_RunNumerical = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.pushButton_RunNumerical.setObjectName("pushButton_RunNumerical")
        self.horizontalLayout_8.addWidget(self.pushButton_RunNumerical)
        self.showLegendNumerical = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        self.showLegendNumerical.setObjectName("showLegendNumerical")
        self.horizontalLayout_8.addWidget(self.showLegendNumerical)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_14.addLayout(self.verticalLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayout_12.addWidget(self.scrollArea_2)
        self.tabWidget_Main.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget_Main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1146, 22))
        self.menubar.setObjectName("menubar")
        self.menuImport = QtWidgets.QMenu(self.menubar)
        self.menuImport.setObjectName("menuImport")
        self.menuCSV = QtWidgets.QMenu(self.menuImport)
        self.menuCSV.setObjectName("menuCSV")
        self.menuPickle = QtWidgets.QMenu(self.menuImport)
        self.menuPickle.setObjectName("menuPickle")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSave = QtWidgets.QMenu(self.menuFile)
        self.menuSave.setObjectName("menuSave")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBrowse = QtWidgets.QAction(MainWindow)
        self.actionBrowse.setObjectName("actionBrowse")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSaveAnalytical = QtWidgets.QAction(MainWindow)
        self.actionSaveAnalytical.setObjectName("actionSaveAnalytical")
        self.actionSaveNumerical_2 = QtWidgets.QAction(MainWindow)
        self.actionSaveNumerical_2.setObjectName("actionSaveNumerical_2")
        self.actionSaveAnalytical_2 = QtWidgets.QAction(MainWindow)
        self.actionSaveAnalytical_2.setObjectName("actionSaveAnalytical_2")
        self.actionCSVNumerical = QtWidgets.QAction(MainWindow)
        self.actionCSVNumerical.setObjectName("actionCSVNumerical")
        self.actionCSVAnalytical = QtWidgets.QAction(MainWindow)
        self.actionCSVAnalytical.setObjectName("actionCSVAnalytical")
        self.actionPklNumerical = QtWidgets.QAction(MainWindow)
        self.actionPklNumerical.setObjectName("actionPklNumerical")
        self.actionPklAnalytical = QtWidgets.QAction(MainWindow)
        self.actionPklAnalytical.setObjectName("actionPklAnalytical")
        self.menuCSV.addAction(self.actionCSVNumerical)
        self.menuCSV.addAction(self.actionCSVAnalytical)
        self.menuPickle.addAction(self.actionPklNumerical)
        self.menuPickle.addAction(self.actionPklAnalytical)
        self.menuImport.addAction(self.menuCSV.menuAction())
        self.menuImport.addAction(self.menuPickle.menuAction())
        self.menuSave.addAction(self.actionSaveNumerical_2)
        self.menuSave.addAction(self.actionSaveAnalytical_2)
        self.menuFile.addAction(self.menuSave.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuImport.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget_Main.setCurrentIndex(1)
        self.tabWidget_Analytical.setCurrentIndex(0)
        self.tabWidget_Numerical.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIMPLUS"))
        self.tabWidget_Analytical.setTabText(self.tabWidget_Analytical.indexOf(self.tab_3), _translate("MainWindow", "Plot"))
        self.tabWidget_Analytical.setTabText(self.tabWidget_Analytical.indexOf(self.tab_4), _translate("MainWindow", "Additional Information"))
        self.tabWidget_Analytical.setTabText(self.tabWidget_Analytical.indexOf(self.tab_5), _translate("MainWindow", "Model Information"))
        self.label.setText(_translate("MainWindow", "Parameter Dictionary"))
        self.treeWidget_Analytical.setSortingEnabled(True)
        self.treeWidget_Analytical.headerItem().setText(0, _translate("MainWindow", "Parameters"))
        self.treeWidget_Analytical.headerItem().setText(1, _translate("MainWindow", "Values"))
        self.treeWidget_Analytical.headerItem().setText(2, _translate("MainWindow", "Units"))
        __sortingEnabled = self.treeWidget_Analytical.isSortingEnabled()
        self.treeWidget_Analytical.setSortingEnabled(False)
        self.treeWidget_Analytical.setSortingEnabled(__sortingEnabled)
        self.pushButtonEmail1.setText(_translate("MainWindow", "Email Notifcation"))
        self.pushButton_RunAnalytical.setText(_translate("MainWindow", "Run"))
        self.showLegendAnalytical.setText(_translate("MainWindow", "Show Legend"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab), _translate("MainWindow", "Analytical"))
        self.tabWidget_Numerical.setTabText(self.tabWidget_Numerical.indexOf(self.tab_7), _translate("MainWindow", "Plot"))
        self.tabWidget_Numerical.setTabText(self.tabWidget_Numerical.indexOf(self.tab_8), _translate("MainWindow", "Additional Information"))
        self.tabWidget_Numerical.setTabText(self.tabWidget_Numerical.indexOf(self.tab_6), _translate("MainWindow", "Model Information"))
        self.comboBox_EquationSolverType.setItemText(0, _translate("MainWindow", "Master Equation Solver"))
        self.comboBox_EquationSolverType.setItemText(1, _translate("MainWindow", "Quantum Jump Solver"))
        self.label_2.setText(_translate("MainWindow", "Parameter Dictionary"))
        self.treeWidget_Numerical.setSortingEnabled(True)
        self.treeWidget_Numerical.headerItem().setText(0, _translate("MainWindow", "Parameters"))
        self.treeWidget_Numerical.headerItem().setText(1, _translate("MainWindow", "Values"))
        self.treeWidget_Numerical.headerItem().setText(2, _translate("MainWindow", "Units"))
        __sortingEnabled = self.treeWidget_Numerical.isSortingEnabled()
        self.treeWidget_Numerical.setSortingEnabled(False)
        self.treeWidget_Numerical.setSortingEnabled(__sortingEnabled)
        self.pushButtonEmail2.setText(_translate("MainWindow", "Email Notification"))
        self.pushButton_RunNumerical.setText(_translate("MainWindow", "Run"))
        self.showLegendNumerical.setText(_translate("MainWindow", "Show Legend"))
        self.tabWidget_Main.setTabText(self.tabWidget_Main.indexOf(self.tab_2), _translate("MainWindow", "Numerical"))
        self.menuImport.setTitle(_translate("MainWindow", "Import"))
        self.menuCSV.setTitle(_translate("MainWindow", "CSV"))
        self.menuPickle.setTitle(_translate("MainWindow", "pickle"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.actionBrowse.setText(_translate("MainWindow", "browse data..."))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSaveAnalytical.setText(_translate("MainWindow", "Save Analytical"))
        self.actionSaveNumerical_2.setText(_translate("MainWindow", "Numerical"))
        self.actionSaveAnalytical_2.setText(_translate("MainWindow", "Analytical"))
        self.actionCSVNumerical.setText(_translate("MainWindow", "Numerical"))
        self.actionCSVAnalytical.setText(_translate("MainWindow", "Analytical"))
        self.actionPklNumerical.setText(_translate("MainWindow", "Numerical"))
        self.actionPklAnalytical.setText(_translate("MainWindow", "Analytical"))

from mplwidget import MplWidgetAnalytic, MplWidgetInfo, MplWidgetNumerical
